const menuItems = [
  {
    key: '/home',
    path: '/home',
    label: 'Inicio',
    icon: 'HomeOutlined',
    description: 'Panel principal de la plataforma',
    roles: [1, 2, 3],
  },
  {
    key: '/chats',
    path: '/chat',
    label: 'Toki',
    icon: 'WechatOutlined',
    description: 'Toki',
    roles: [1],
  },
  {
    key: 'administracion',
    label: 'Administración',
    icon: 'SettingOutlined',
    path: '/administracion',
    roles: [1, 2],
    children: [
      {
        key: '/usuarios',
        path: '/administracion/usuarios',
        label: 'Usuarios',
        icon: 'UserAddOutlined',
        description: 'Registrar nuevos usuarios en el sistema',
        roles: [1],
      },
      {
        key: '/campanas',
        path: '/administracion/campanas',
        label: 'Campañas',
        icon: 'AppstoreAddOutlined',
        description: 'Gestión de campañas disponibles',
        roles: [1],
      },
      {
        key: '/areas',
        path: '/administracion/areas',
        label: 'Áreas',
        icon: 'DeploymentUnitOutlined',
        description: 'Gestión de áreas organizacionales',
        roles: [1],
      },
      {
        key: '/roles',
        path: '/administracion/roles',
        label: 'Roles',
        icon: 'TeamOutlined',
        description: 'Administración de roles y permisos',
        roles: [1, 2],
      },

    ],
  },
  {
    key: 'Automatizaciones',
    label: 'Automatizaciones',
    icon: 'LaptopOutlined',
    roles: [1],
    children: [
      {
        key: '/rpaFamisanar',
        path: '/salud/rpaFamisanar',
        label: 'Rpa FamiSanar',
        icon: 'IdcardOutlined',
        description: 'Automatización del proceso de consulta de la EPS Famisanar',
        roles: [1],
      },
      {
        key: '/rpaNuevaEps',
        path: '/salud/rpaNuevaEps',
        label: 'Rpa Nueva Eps',
        icon: 'IdcardOutlined',
        description: 'Automatización del proceso de consulta de la EPS Nueva EPS',
        roles: [1],
      },
      {
        key: '/rpaWhatsApp',
        path: '/rpaWhatsApp',
        label: 'Rpa WhatsApp',
        icon: 'WhatsAppOutlined',
        description: 'Automatización del proceso de consulta y registro de disponibilidad de números en WhatsApp',
        roles: [1],
      },
      {
        key: '/rpaSuperNotariado',
        path: '/juridica/rpaSuperNotariado',
        label: 'Super Notariado',
        icon: 'AuditOutlined',
        description: 'Automatización de consulta de información registral en la Superintendencia de Notariado y Registro.',
        roles: [1, 16],
      },
      {
        key: '/rpaRunt',
        path: '/juridica/rpaRunt',
        label: 'Runt',
        icon: 'FileSearchOutlined',
        description: 'Automatización del proceso de consulta y registro del Registro Único Nacional de Tránsito.',
        roles: [1, 16],
      },
      {
        key: '/rpaRues',
        path: '/juridica/rpaRues',
        label: 'Rues',
        icon: 'ApartmentOutlined',
        description: 'Automatización de consulta y procesamiento del Registro Único Empresarial y Social',
        roles: [1, 16],
      },
      {
        key: '/rpaSimit',
        path: '/juridica/rpaSimit',
        label: 'Simit',
        icon: 'CarOutlined',
        description: 'Automatización del proceso de consulta y registro de información del SIMIT',
        roles: [1, 16],
      },
      {
        key: '/rpaVigilancia',
        path: '/juridica/rpaVigilancia',
        label: 'Vigilancia',
        icon: 'AlertOutlined',
        description: 'Automatización del proceso de consulta, seguimiento y registro de información jurídica',
        roles: [1, 16],
      },
      {
        key: '/rpaCamaraComercio',
        path: '/juridica/rpaCamaraComercio',
        label: 'Cámara de Comercio',
        icon: 'AlertOutlined',
        description: 'Automatización del proceso de consulta directamente en la Cámara de Comercio',
        roles: [1, 16],
      },
      {
        key: '/rpaJuridico',
        path: '/juridica/rpaJuridico',
        label: 'Juridico',
        icon: 'AlertOutlined',
        description: 'Automatización del proceso de consulta, seguimiento y registro de información jurídica',
        roles: [1, 16],
      },
      {
        key: '/rpaTyba',
        path: '/juridica/rpaTyba',
        label: 'Tyba',
        icon: 'AlertOutlined',
        description: 'Automatización del proceso de consulta judicial (Tyba)',
        roles: [1, 16],
      },
      {
        key: '/rpaVigencia',
        path: '/juridica/rpaVigencia',
        label: 'Vigencia de Cedula',
        icon: 'AlertOutlined',
        description: 'Automatización del proceso de consulta de vigencia de cédulas',
        roles: [1, 16],
      },
      {
        key: '/rpaMensajesWhatsApp',
        path: '/rpaMensajesWhatsApp',
        label: 'Rpa Mensajes WhatsApp',
        icon: 'WhatsAppOutlined',
        description: 'Rpa Mensajes WhatsApp',
        roles: [1],
      },
    ],
  },
   {
    key: 'gail',
    label: 'GAIL',
    icon: 'CalendarOutlined',
    path: '/gail',
    roles: [1],
    children: [
      {
        key: 'campañas',
        path: '/gail/campañas',
        label: 'Campañas Gail',
        icon: 'UploadOutlined',
        description: 'Crear Campaña en Gail',
        roles: [1],
      },
      {
        key: '/conversor',
        path: '/conversor',
        label: 'Conversor',
        icon: 'EditOutlined',
        description: 'Módulo de estandarización de datos que convierte valores numéricos a texto y normaliza nombres',
        roles: [1],
      },
    ],
  },
  
  {
    key: '/tableroControl',
    path: '/tableroControl',
    label: 'Tableros de Control',
    icon: 'BarChartOutlined',
    description: 'Tablero de control',
    roles: [1, 12],
    children: [
      {
        key: '/tableroControl',
        path: '/tableroControl',
        label: 'Tablero Control',
        icon: 'BarChartOutlined',
        description: 'Tablero Control',
        roles: [1],
      },
      {
        key: '/controlRpa',
        path: '/controlRpa',
        label: 'Tablero Control RPA',
        icon: 'BarChartOutlined',
        description: 'Tablero Control RPA',
        roles: [1],
      },
      {
        key: '/tableroEmbudo',
        path: '/tableroEmbudo',
        label: 'Tablero Contacto',
        icon: 'PhoneOutlined',
        description: 'Tablero Contacto',
        roles: [1],
      },
    ],
  },
  {
    key: 'notificaciones',
    label: 'Notificaciones',
    icon: 'BellOutlined',
    path: '/notificaciones',
    roles: [8],
    children: [
      {
        key: '/sms',
        path: '/notificaciones/SMS',
        label: 'SMS',
        icon: 'MessageOutlined',
        description: 'Envio de SMS',
        roles: [8],
      },
    ],
  },
  {
    key: 'planeacions',
    label: 'Planeacion',
    icon: 'CalendarOutlined',
    path: '/planeacion',
    roles: [1],
    children: [
      {
        key: '/focosTrabajable',
        path: '/planeacion/focosTrabajable',
        label: 'Focos Trabajable',
        icon: 'DatabaseOutlined',
        description: 'Uso de la tabla trabajables completa',
        roles: [1],
      },
      {
        key: '/focosResultado',
        path: '/planeacion/focosResultado',
        label: 'Focos Resultado',
        icon: 'BarChartOutlined',
        description: 'Uso de la tabla de resultados',
        roles: [1],
      },
    ],
  },

  {
    key: 'juridica',
    label: 'Juridica',
    icon: 'FileProtectOutlined',
    path: '/juridica',
    roles: [1],
    children: [
      {
        key: '/impulsoProcesal',
        path: '/juridica/impulsoProcesal',
        label: 'Impulso Procesal',
        icon: 'FileSearchOutlined',
        description: 'Impulso Procesal',
        roles: [1],
      },
    ],
  },
  {
  
        key: '/EmailMasivo',
        path: '/EmailMasivo',
        label: 'Email Masivo',
        icon: 'SendOutlined',
        description: 'Envia correos personalizados masivamente',
        roles: [1],
      },
    
  
      {
        key: '/mensajesWhatsApp',
        path: '/mensajesWhatsApp',
        label: 'Mensajes WhatsApp',
        icon: 'WhatsAppOutlined',
        description: 'Envia mensajes de WhatsApp personalizados masivamente',
        roles: [1],
      },
    
      {
        key: '/acuerdoPago',
        path: '/acuerdoPago',
        label: 'Cargue Acuerdo de Pago',
        icon: 'UploadOutlined',
        description: 'Cargue Acuerdo de Pago a Teseo',
        roles: [1],
      },
  
];

export default menuItems;
